# Generated by Django 2.0.7 on 2018-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_user_name', models.CharField(max_length=50)),
                ('r_password', models.TextField(max_length=150)),
                ('r_email', models.DateTimeField(max_length=200)),
            ],
        ),
    ]
