# Generated by Django 2.0.7 on 2018-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_user_name', models.CharField(max_length=50)),
                ('r_password', models.TextField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='login',
            new_name='login_fform',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
